.github/actions/spell-checker/ignore_words.txt
.github/workflows/grammar-spell-checker.yml
README.md

Open graph instructions.
- Introduces metadata
- Introduces open graph metadata and its origins
- Provides a preview/debugger tool
- Provides a troubleshooting guide
- [PRO-176](https://linear.app/fleekxyz/issue/PRO-176/add-open-graph-instructions)

docs: 📝 open graph instructions

---

src/layouts/BaseHtml.astro

Use open graph title and meta in base title and desc
- Override base site title and description
- [PRO-181](https://linear.app/fleekxyz/issue/PRO-181/custom-metadata-for-base-pages)

chore: 🤖 use open graph title and meta in base title and desc

---

src/content/docs/index.mdx
src/layouts/BaseHtml.astro
src/layouts/DocPage.astro
src/layouts/Page.astro
src/pages/blog.astro
src/pages/blog/[category].astro
src/pages/docs/[...slug].astro
src/pages/docs/index.astro
src/pages/guides.astro
src/pages/index.astro
src/pages/pricing.astro
src/pages/references.astro
src/settings.json

Custom base page descriptions
- Split base pages by named settings
- Use named setting per page name
- Tweak content title for doc main
- [PRO-181](https://linear.app/fleekxyz/issue/PRO-181/custom-metadata-for-base-pages)

refactor: 💡 custom base page descriptions

---

README.md
Services/ZenDesk/api.ts
Services/ZenDesk/nginx.conf
Services/ZenDesk/support.service

Prepare support for production
- Document the server setup process, e.g. systemd, NGINX, etc
- Provide reference configuration files for systemd, NGINX
- [AS-86](https://linear.app/fleekxyz/issue/AS-86/create-production-server-for-supportzendesks)

chore: 🤖 prepare support for production

---

pnpm-lock.yaml
src/components/GlobeWithFloatingCards.tsx

close PLAT-1031
https://github.com/fleek-platform/website/assets/52458215/03157c8b-6a08-46d9-9f94-2ab9fdd06fed

feat: Replace 'Stay updated' link on fleek.xyz with a link to /docs

---

src/content/docs/CLI/Functions/index.md

Added documentation on how to use environment variables in Fleek Functions.
- Updated `src/content/docs/CLI/Functions/index.md`
- [PLAT-974](https://linear.app/fleekxyz/issue/PLAT-974/improvement-for-fleek-functions-documentation)

docs: How to use environment variables inside functions

---

README.md
Services/ZenDesk/api.ts
Services/ZenDesk/utils.ts

Support service allowances for staging and production
- Extend support custom env vars
- Utility helpers to get user env vars
- Update documentation
- [AS-277](https://linear.app/fleekxyz/issue/AS-277/support-service-allowances-for-staging-and-production)
N/A

refactor: 💡Support service allowances for staging and production

---

src/components/Footer/config.ts

fix(footer): update "Contact us" Link

---

src/content/guides/solana-blinks-on-fleek/index.md

chore: spell fix

---

src/components/Footer/index.tsx

Align x icon color
close PLAT-873
- Done B
- Done C
DEMO
https://github.com/user-attachments/assets/d82a8825-5cfe-4113-a71a-faa370f3d316

fix: fix x logo color

---

src/components/NavBar/component.css
src/components/NavBar/index.tsx

before/after
https://github.com/user-attachments/assets/9cf5b95a-c8f3-4494-9532-cb7309aaed9f

fix: burger shift

---

src/components/NavBar/component.css
src/components/NavBar/index.tsx

follow-up to https://github.com/fleek-platform/website/pull/112
https://github.com/user-attachments/assets/e5e20860-1d37-4387-b790-2e879ea33945

fix: burger shift followup

---

Services/ZenDesk/api.ts
Services/ZenDesk/routes.ts

We needed to add endpoints for Zendesk to support client-side operations, including file uploads and hitting the requests endpoint.
1. Add the necessary routes in the server to handle client-side requests.
2. Implement the file upload functionality, ensuring the server can accept and process files.
3. Connect the file upload endpoints to the Zendesk API, ensuring proper authentication and data handling.
- [PLAT-1093](https://linear.app/fleekxyz/issue/PLAT-1093/develop-a-project-plan-for-the-seamless-community-feedback-form)
- [] Sensitive data has been identified and is being protected properly
[Requests endpoint](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket-requests/)
[Uploads endpoint](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket-attachment …

feat: Add zendesk api routes

---

src/components/ButtonYellow.tsx
src/components/Changelog/ChangelogListBody.astro
src/components/Footer/config.ts
src/components/IconArrow.tsx
src/components/NavBar/config.ts
src/layouts/ChangelogListPage.astro
src/layouts/DocPage.astro
src/pages/changelog.astro
src/settings.json
src/styles/changelogList.css

- This PR adds the changelog list page, base components and styling
https://github.com/user-attachments/assets/c5d8a7d0-d3b0-492f-9ebf-8fccaf493036
- [AS-286](https://linear.app/fleekxyz/issue/AS-286/implement-the-changelog-page)

feat(changelog): add changelog list page

---

src/components/Changelog/ChangelogItem.astro
src/pages/api/changelog-batch/[batch].astro
src/pages/changelog.astro

feat: Added pre-generated Changelog batch

---

src/content/docs/CLI/Functions/index.md

docs: adding ts support for fleek functions

---

package-lock.json
package.json
src/content/config.ts

Upgrade astro next minor version
- Upgrade Astro next minor version
- Update type in collection
- [AS-319](https://linear.app/fleekxyz/issue/AS-319/update-createcollection-to-use-the-new-syntax-changes-of-astro-zods)

refactor: 💡 upgrade astro next minor version

---

src/content/blog/learn/vercel-alternatives-guides/index.md

Start for free had ** at the start and end. Just put it all bold without the **
- Done B
- Done C

chore: Update blog link

---

src/content/blog/learn/vercel-alternatives-guides/index.md

- Done B
- Done C
- before 
- after

chore: fix blog link

---

src/styles/globals.css

fix: revert overflow x hidden back to html, body

---

src/layouts/LandingPage.astro
src/styles/globals.css

fix: add overflow to landing page and remove from docs

---

src/components/Button.tsx
src/components/PricingCard.tsx
src/content/pricing/config.ts
tailwind.config.mjs

- Updates pricing card styling at `/pricing`
- Updated styles.
N / A
| Before | After |
| ------- | ----- |
| <img width="1440" alt="Screenshot 2024-11-12 at 1 36 59 PM" src="https://github.com/user-attachments/assets/560e464a-86ab-45bd-a897-57170d7066de"> | <img width="1440" alt="Screenshot 2024-11-12 at 1 35 50 PM" src="https://github.com/user-attachments/assets/4edcf501-83ef-4ea4-81b8-37de5b972e63"> | 

feat: 🎸 Updated pricing card styling

---

src/components/Pricing/Table/constants.ts
src/content/pricing/config.ts

Updates link to billing on dashboard.
- Replaced occurrences of the previous link with the new one.
N/A

chore: 🤖 Update billing url to dashboard

---

src/content/blog/announcements/fleek-machines-fleek-functions/index.md

fix: re-trigger main build

---

src/components/Sidebar.tsx
src/components/Support/config.ts

Need to fix redirected urls
add a /

fix(NA): update support links

---

src/content/docs/Deploy_AI_Agents/index.mdx
src/settings.json

simple coming soon page for ai agent deployments

feat: add coming soon for ai agent deployments in docs

---

src/components/Eliza/hooks/useDeployAIAgent.ts
src/components/Eliza/index.tsx

fix(eliza): :fire: remove cancel deployment functionality

---

Services/ZenDesk/README.md
src/content/references/faq/github-account-limitations/index.md

Incorrect information on the docs
Replaced the information with the correct one
No ticket
https://fleek.xyz/references/faq/github-account-limitations/

chore: update index.md to correct github reference

---

src/utils/cookies.ts
src/utils/url.ts

The access token should be made available cross-domain. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent
- Pass "Domain" attribute to cookie
- [PLAT-1960](https://linear.app/fleekxyz/issue/PLAT-1960/cross-domain-cookie-availability)

chore: 🤖 Cross-domain cookie availability

---

src/components/LandingPage/PricingLanding.tsx
src/components/LandingPage/Text.tsx
src/components/Pricing/PricingPlanHero.tsx
src/components/Pricing/index.tsx
src/components/PricingCard.tsx
src/content/pricing/config.ts

- Updates pricing panel on pricing page and landing page
- [PLAT-1954](https://linear.app/fleekxyz/issue/PLAT-1954/update-pricing-panel-on-pricing-and-landing-page-with-new-ai-agent)

feat(eliza): update pricing panel on pricing and landing page with new ai agents

---

src/components/Eliza/CoreEliza.tsx
src/components/Eliza/components/Button.tsx
src/components/Eliza/components/Characterfile.tsx
src/components/Eliza/components/DeploymentFailed.tsx
src/components/Eliza/components/DeploymentStatus.tsx
src/components/Eliza/components/Navigation.tsx
src/components/Eliza/components/ReviewPage.tsx
src/components/Eliza/components/SettingsPage.tsx
src/components/Eliza/components/Step.tsx
src/components/Eliza/components/UploadPage.tsx
src/components/Eliza/utils/types.ts

- Lifted navigation state to CoreEliza
- Refactored syncs through the inner pages to fix race conditions
- Changed copy per Nate request on some labels to make them more user friendly
- Tweaked some visuals so we have more consistency across the flow
https://ancient-pizza-rapid.on-fleek.app/eliza

refactor(eliza): navigation state and small improvements

---

src/settings.json

fix: :bug: fix eliza's og image name

---

README.md

Add dynamic environment ID
- Update documentation
n/a

docs: 📝 Add dynamic environment IDs

---

src/components/Eliza/utils/constants.ts

- Adds `POST_IMMEDIATELY: 'true'` to settings when users pick Twitter
- Done B
- Done C

chore(eliza): add post immediately to twitter

---

README.md
src/components/AuthProvider/api/api.ts
src/settings.json

Missing env var causes incorrect calls.
- Update documentation example
- Throw on missing

fix: 🐛 Missing env var causes incorrect calls

---

src/components/Eliza/utils/constants.ts

Fixed the environment variables needed for the lens and added together the model.
- Done B
- Done C

fix(eliza): Fixed Lens and Together issue

---

src/components/Eliza/CoreEliza.tsx

fix(copy): :speech_balloon: update message when deployment fails

---

README.md
Services/Beehiiv/.gitignore
Services/Beehiiv/README.md
Services/Beehiiv/packages/main/create-subscription/index.js
Services/Beehiiv/packages/main/create-subscription/package.json
Services/Beehiiv/project.yml

Beehiiv proxy server as DigitalOcean function
- Create proxy server in Services/Beehiiv
- [PLAT-1985](https://linear.app/fleekxyz/issue/PLAT-1985/proxy-server-for-beehiiv)

feat: 🎸 Beehiiv proxy server as DigitalOcean function

---

src/settings.json

The link for "Report abuse" on the footer was not correct
- Replaced the link on #L146

fix: 🐛 Update settings.json - Replaced the link on #L146

---

src/components/Eliza/components/Navigation.tsx

fix: :bug: add safeguard for object prop validation

---

src/layouts/LandingPageHtml.astro

feat: add promote kit script to landing page

---

src/components/Eliza/api/index.ts
src/components/Eliza/components/SubscriptionModal.tsx

chore: send referral id in the api

---

package-lock.json
package.json

- Bumping to `1.4.3`
- Done B
- Done C

chore(eliza): bump agents-ui package

---

src/content/docs/SDK/Fleek_Functions/index.md
src/content/docs/SDK/index.md
src/content/troubleshooting/eliza/eliza-deployment-troubleshooting/index.md

Added docs for Fleek functions via the SDK and updated the troubleshooting guide with updated information on Twitter auth issues.

docs: ✏️ added docs for fleek functions via sdk and fixed troubleshooting guide

---

package-lock.json
package.json

This pull request updates the agents UI module to the latest version for release.
https://github.com/user-attachments/assets/607c71e9-ecf8-4d13-a632-de5efaa69cd8

feat: update agents UI module

---

package-lock.json
package.json

This version bump brings in the a text change fix for the Twitter client:
https://github.com/user-attachments/assets/263a1a86-6791-458f-b2d4-6eb073c12851

chore: 🤖  upgrade agents UI module 2.2.6

---

src/content/docs/ai-agents/Agent-Logs/index.mdx
src/content/docs/ai-agents/Agents-APIs/index.mdx
src/content/docs/ai-agents/Build From Scratch/index.mdx
src/content/docs/ai-agents/Model_Providers/index.mdx
src/content/docs/ai-agents/Select Template/index.mdx
src/content/docs/ai-agents/Troubleshoot/index.mdx
src/content/docs/ai-agents/index.mdx
src/content/docs/ai-agents/plugins/index.mdx

This PR provides fixes for the docs typos and some other docs adjustments for the Eliza agent hosting documentation setup/

docs: fix notes typo and adjust docs

---

src/content/docs/ai-agents/Upload Characterfile/index.mdx

This fixes a typo issue on the upload characterfile page of the agents deployment docs

docs: fix upload characterfile typo

---

package-lock.json
package.json

This pull request adds in support for the support template:
https://github.com/user-attachments/assets/557d883f-0568-42c3-a032-bdd2f227833e

chore: 🤖  add support template

---

package-lock.json
package.json
src/components/AgentsUI/index.tsx
src/pages/eliza.astro

Update Agents AI to v3.5.0
-  Update package
- [PLAT-2156](https://linear.app/fleekxyz/issue/PLAT-2156/update-agents-ui-v350)

chore: 🤖 Update Agents AI to v3.5.3

---

package-lock.json
package.json
src/components/AgentsUI/index.tsx
src/pages/eliza.astro

Update Agents AI to v3.5.x
⚠️ Related to https://github.com/fleek-platform/agents-ui/pull/69
⚠️ Related to https://github.com/fleek-platform/website/pull/508
-  Update package
- [PLAT-2156](https://linear.app/fleekxyz/issue/PLAT-2156/update-agents-ui-v350)
> The current staging environment (https://fleek-xyz-staging.fleeksandbox.xyz/) on Firefox causes:

chore: 🤖 update agents UI v3.5.4

---

package-lock.json
package.json

Updates @fleek-platform/agents-ui to v3.8.2
ref:
https://github.com/fleek-platform/agents-ui/commit/961a3b94eb0e4c1e38ff63ae5be41a1785eb2840
https://github.com/fleek-platform/agents-ui/commit/b77ab7780d4ba9cd3901caeeaa6fb97a32af5a91
https://github.com/fleek-platform/agents-ui/commit/37fca48b2f18f0bb176e5bf0b5e432efe01eb229
https://github.com/fleek-platform/agents-ui/commit/711ad681858edac7a3a59fd17d89744effac0053
- update package and package.lock

chore: update agents-ui to 3.8.2

---

package-lock.json
package.json

Updates @fleek-platform/agents-ui to 3.8.5
ref:
https://github.com/fleek-platform/agents-ui/commit/f0f28e36cb074cf1410ed6fb54adf1daaed29c4e
https://github.com/fleek-platform/agents-ui/commit/5d84b75a86aae05b66bf2477a5e2106ba5e1e5b5
- Updated package and package-lock

chore: update agents-ui to 3.8.5

---

package-lock.json
package.json

Fixes bug that prevented avatar to be saved on first submit.
- Bumped to  `agents-ui` version which includes the fix [See PR](https://github.com/fleek-platform/agents-ui/pull/80)
N/A

chore: 🤖 Bump agents-ui to 3.8.6

---

package-lock.json
package.json

https://github.com/user-attachments/assets/e84745cc-32f3-411c-aa7b-8c182c7e3faf

chore: 🤖  bump agents ui packages

---

package-lock.json
package.json
src/components/Tracking/trackingUtils.ts

chore(eliza): bump agenst-ui dep and adjust analytics

---

package-lock.json
package.json
src/pages/eliza.astro

- Simplifies Eliza base layout
- Created in coordination with https://github.com/fleek-platform/agents-ui/pull/86
- Bumps `agents-ui` package to `3.10.0`
https://github.com/user-attachments/assets/73ce91d8-856d-40da-8341-985acbcee143
- [PLAT-2174](https://linear.app/fleekxyz/issue/PLAT-2174/agents-ui-eliza-design-changes)

style: update eliza layout

---

src/components/Agents/components/NewsletterModal/components/Box.tsx
src/components/Agents/components/NewsletterModal/components/Button.tsx
src/components/Agents/components/NewsletterModal/components/Input.tsx
src/components/Agents/components/NewsletterModal/components/Modal.tsx
src/components/Agents/components/NewsletterModal/components/Text.tsx
src/components/Agents/components/NewsletterModal/hooks/useBeehiiv.ts
src/components/Agents/components/NewsletterModal/hooks/useDisableScroll.ts
src/components/Agents/components/NewsletterModal/hooks/useOnKeyDown.ts
src/components/Agents/components/NewsletterModal/index.tsx
src/components/Agents/index.tsx
src/pages/agents.astro

Added subscribe newsletter modal
https://github.com/user-attachments/assets/7814c231-0b62-4ed2-b8bf-b1a109c7e6e4
- Done B
- Done C

feat: add subscribe newsletter modal

---

src/content/docs/ai-agents/index.mdx
src/content/docs/index.mdx

This pull request adds in CTAs for the AI  Agent hosting for enterprises.

docs: add cta

---

src/content/docs/ai-agents/Agent-Logs/index.mdx
src/content/docs/ai-agents/Agents-APIs/index.mdx
src/content/docs/ai-agents/index.mdx

This pull request adds in feedback on the latest docs updates pushed to the Fleek.xyz docs

docs: add feedback updates

---

package-lock.json
package.json

This PR adds in the web starter template to the frontend.

chore: 🤖 bump eliza ui module to add web3 starter pack

---

package-lock.json
package.json

Reverts fleek-platform/website#549

chore: Revert "chore: 🤖 bump eliza ui module to add web3 starter pack"

---

package-lock.json
package.json

Updates agents-ui to 4.4.0.
agents-ui 4.3.4~4.4.0 diff:
https://github.com/fleek-platform/agents-ui/compare/28104b92b744447a465ee05d4b92664044e91d56..7c0e31d877164e14affb4a7242126e9ddc386ea2
- Update package
- Update package-lock

chore: update agents-ui to 4.4.0

---

package-lock.json
package.json

Updates agents-ui to 4.6.2.
agents-ui 4.4.0~4.6.2 diff:
https://github.com/fleek-platform/agents-ui/compare/7c0e31d877164e14affb4a7242126e9ddc386ea2..96a010154803dc27048a81ff7cc6d5dfe8848dae
- Update package
- Update package-lock

chore: update agents-ui to 4.6.2

---

src/components/Navbar/config.ts
src/components/Navbar/index.tsx
src/settings.json

Dashboard URL as environment variable.
- Remove URL from settings.json
- Use environment variable
- [AS-393](https://linear.app/fleekxyz/issue/AS-393/website-dashboard-url-should-be-computed-from-environment-variable)

refactor: 💡 Dashboard URL as environment variable

---

src/content/docs/Platform/Billing/index.mdx
src/content/docs/SDK/Fleek_Functions/index.md

This pull request adds in documentation fixes and updates for some housekeeping and new docs addition work.
- [Update fleek.xyz/docs to remove references to Free Plan and add references to 7-day free trial of Pro Plan](https://linear.app/fleekxyz/issue/PLAT-2329/update-fleekxyzdocs-to-remove-references-to-free-plan-and-add)
- [Update FAQ to remove references to Free Plan and also surface information on free trial](https://linear.app/fleekxyz/issue/PLAT-2330/update-faq-to-remove-references-to-free-plan-and-also-surface)

docs: add Fleek SDK for Fleek Functions example usage

---

src/content/troubleshooting/eliza/eliza-deployment-troubleshooting/index.md

It was wrong, missing a space
- Done B
- Done C

docs: fixed eliza troubleshooting guide twitter 2fa code

---

README.md
package-lock.json
package.json
src/components/AnnouncementModal/index.tsx
src/settings.json

Adjusted text of "at capacity" modal just in case we need it;
Made the "modal show delay" and "modal dismissed expiry" configurable from the settings
Bumped `agents-ui` version to the latest.
- Done B
- Done C

chore(announcements): Adjust announcement modal; bump agents-ui dep

---

package-lock.json
package.json

chore(dependencies): :arrow_up: Upgrade login-button dep version

---

package-lock.json
package.json

Update Agents UI to v4.12.1
- Done B
- Done C

chore: 🤖 Update Agents UI to v4.12.1

---

package-lock.json
package.json
src/components/AgentsUI/index.tsx

Update agents UI v6.6.0
- Done B
- Done C

chore: 🤖 Update agents UI v6.6.0

---

src/content/docs/ai-agents/index.mdx

We do not support Eliza v0.25.9 yet. A user already was confused by this.
- Done B
- Done C

docs: Update AI Agents docs Eliza supported version

---

src/content/guides/fleek-ai-agents-api/index.md

It's wrong in scalar, should be PUT request.
- Done B
- Done C

docs: replaced POST with PUT on Create payment portal session

---

src/components/Tracking/Trackers.astro
src/layouts/BaseHtml.astro
src/layouts/ElizaHtml.astro
src/layouts/LandingPageHtml.astro

- Replaces promotekit script tag with tolt as our main affiliate program
- [PLAT-2485](https://linear.app/fleekxyz/issue/PLAT-2485/incorporate-affiliate-program-to-app-and-landing)

chore: switch promotekit with tolt affiliate program

---

package-lock.json
package.json

bump dashboard version
- Done B
- Done C

chore: bump dashboard version

---

README.md
src/env.d.ts

Package is independent now
- Done B
- Done C

chore: 🤖 Removed `agents-ui` env variables

---

src/components/Button.tsx
src/components/Footer/index.tsx
src/components/LandingPage/AgentsVideo.tsx
src/components/LandingPage/Hero.tsx
src/components/LandingPage/IdeaToAgentSteps.tsx
src/components/LandingPage/PricingCalculator/config.ts
src/components/LandingPage/PricingCalculator/index.tsx
src/components/LandingPage/Text.tsx
src/hooks/useDeployAgentCta.ts
src/layouts/LandingPageHtml.astro
src/pages/index.astro

feat: pricing section

---

src/components/Agents/index.tsx
src/components/LandingPage/Hero.tsx
src/hooks/useLoginWithAgentsCTA.ts

Agents page should open login modal
- Created a hook
-  [AS-399](https://linear.app/fleekxyz/issue/AS-399/website-agents-page-the-create-agent-should-call-authenticate-first)

fix: 🐛 Agents page should open login modal

---

src/settings.json

- Done B
- Done C
- [PLAT-2626](https://linear.app/fleekxyz/issue/PLAT-2636/website-fix-support-link)

chore: remove unused support urls

---

package-lock.json
package.json

feat(deps): upgrade agents-ui version to 7.20.0

---

package-lock.json
package.json

chore(dep): upgrade agents-ui dep to 7.21.0

---

package-lock.json
package.json

chore(deps): upgrade agents-ui dep 7.21.1

---

package-lock.json
package.json

chore(deps): upgrade agents ui dep 7.23.0

---

package-lock.json
package.json

chore(deps): agents ui dep revert to 7.15.6

---

src/components/Autofun.tsx

fix: img path

---

src/components/Autofun.tsx
src/pages/autofun.astro
src/settings.json

- Centers optically the page with a small bump in the padding bottom
- Adds dedicated metadata in settings for further tweaks
- Done B
- Done C

chore: autofun tweaks

---

package-lock.json
package.json

chore: 🤖 Bump agents-ui to 7.27.0

---

package-lock.json
package.json

chore: 🤖 Bump agents to 8.2.4

---

package-lock.json
package.json

chore: bump agents package to 8.2.5

---

package-lock.json
package.json
src/settings.json

chore: bump agents-ui to 8.3.1

---

package-lock.json
package.json

chore: bump agents-ui to 8.3.2

---

src/components/LandingPage/Faq/config.ts
src/components/LandingPage/Faq/index.tsx
src/pages/index.astro

Adds FAQ with updated content per Nate review
- [PLAT-2801](https://linear.app/fleekxyz/issue/PLAT-2801/replace-faq-copy-lorem-ipsum-with-content)

chore: FAQ updated with real content

---

src/content/blog/announcements/coinlist-community-round/index.md

chore: hotfixes blog file extension

---

src/components/LandingPage/Content.tsx
src/components/LandingPage/Earn.tsx
src/components/LandingPage/Templates.tsx
src/content/blog/announcements/coinlist-community-round/index.md
src/pages/index.astro

- Removes interactivit from inactive buttons
- Done B
- Done C

chore: disable interaction for inactive buttons

---

src/components/PricingCard.tsx
src/content/pricing/config.ts
src/pages/index.astro

fix: fix link to agents

---

package-lock.json
package.json
src/components/Navbar/index.tsx

chore: bump agents to `8.8.6`

---

src/components/Announcement.tsx

- Done B
- Done C
before
---
after

fix(docs): announcement style

---

src/components/Autofun.tsx

chore: change copy from $10 to $20/m in autofun page

---

src/components/LandingPage/Templates.tsx

- Adds a loader to avoid layout shifts from the slider lib
- Adds a plugin to manage autoscrolling, which is paused when user hovers
Demo (ps: I'm refreshing page twice in the beginning)
https://github.com/user-attachments/assets/e6413064-df39-43cd-a0bd-079c339cd6a6

style: explore section enhancements

---

src/components/Navbar/index.tsx

chore(PLAT-2520): point navbar links to agents-ui

---

src/content/docs/Platform/Billing/index.mdx

Free plan is deprecated, need to update the docs-
- Done B
- Done C

docs: Update index.mdx platform-billing

---

package-lock.json
package.json
src/components/Tracking/Trackers.astro

chore(deps): bump agent-ui to 8.20.1

---

package-lock.json
package.json

chore(deps): bump agents-ui package to 8.21.2

---

package-lock.json
package.json

chore(deps): bump agents-ui package to 8.23.0

---

package-lock.json
package.json

chore: bump agents-ui

---

src/components/Navbar/index.tsx
src/hooks/useDeployAgentCta.ts
src/hooks/useLoginWithAgentsCTA.ts
src/pages/eliza.astro

Rename env variables for Agents UI
N/A
- [PLAT-2904](https://linear.app/fleekxyz/issue/PLAT-2904/website-rename-env-variables-for-agents-ui-to-lates-convention)

fix: 🐛 Rename env variables for Agents UI

---

src/components/ChatToAIAgentDeploy/index.tsx

Remove setDefined calls as side effect
- Remove use effect calls
- [PLAT-2905](https://linear.app/fleekxyz/issue/PLAT-2905/agents-ui-on-site-remove-setdefined-calls-as-side-effect)

chore: 🤖 Remove setDefined calls as side effect

---

package-lock.json
package.json

chore(dep): bump dashboard dep to 0.20.9

---

package-lock.json
package.json
src/components/Navbar/config.ts
src/components/Pricing/PricingPlanHero.tsx
src/content/pricing/config.ts
src/utils/templates.ts

fix(NA): fix links due to domain migration

---

src/components/Navbar/config.ts
src/content/pricing/config.ts
src/utils/templates.ts

fix(NA): condition to detect for resources instead of hosting

---

package.json

chore: bump dashboard@ to 0.20.11

---

src/components/Footer/config.ts

fix: footer

---

src/components/Footer/config.ts
src/components/Navbar/config.ts

fix: eliza docs links

---

package-lock.json
package.json

feat: upgrade dashboard to 0.21.2

---

package-lock.json
package.json

feat: upgrade dashboard to 0.21.5

---

package-lock.json
package.json

fix: redirection
