src/content/docs/Platform/Projects/index.mdx
src/content/docs/SDK/index.md

We need to let users know that Application credentials cannot be used for any SDK method but their purpose is limited to file upload.
- Change in src/content/docs/Platform/Projects/index.mdx
- Change in src/content/docs/SDK/index.md

docs: 📝 add information that Application credentials are limited to file upload

---

src/pages/blog/[category].astro
src/settings.json

Add support for custom category metadata
- Introduce custom blog category meta fields
- [PRO-192](https://linear.app/fleekxyz/issue/PRO-192/add-support-for-custom-category-metadata)

chore: 🤖 add support for custom category metadata

---

src/components/BlogPosts.astro
src/pages/blog/[...slug].astro
src/styles/blogPage.css
src/utils/date.ts

Currently, we are not exposing the publish date of our content. We should use the date from the blog post entries to surface it in the blog gallery and blog post pages.
- Added a helper `formatDate` that takes a date (`Date`) and optional options (`Intl.DateTimeFormatOptions`) to output a user friendly date like `May 10, 2024`
- Added the formatted date from the blog entries into the page `[...slug].astro` and the component `BlogPosts.astro`
- Iterated a bit style-wise to make the date more harmonic with the other elements
- [PRO-194](https://linear.app/fleekxyz/issue/PRO-194/add-publish-date-to-blog-gallery-and-blog-post-pages)
| Before | After |
|--------|------|
| <img width="1451" alt="image" …

feat: 🎸 add date to blog gallery and blog post pages

---

src/components/Footer/config.ts
src/components/NavBar/config.ts

Currently, our inline links are title cased. We would like to have them sentence case instead.
i.e.: `Support Center` -> `Support center`
- Manual changing some capital letters 😭 
- [AS-212](https://linear.app/fleekxyz/issue/AS-212/[in-blog-docs-landing-page]-sentence-case-all-inline-links)

chore: 🧹 sentence case all inline links

---

.github/actions/spell-checker/ignore_words.txt
src/content/docs/Platform/Storage/index.mdx

We need to let users know about the Fleek storage limitations that we have imposed this week.
- Add a warning about a upload daily quota that is 150 files of 2GB size per 24 hours
- Add a warning about a limitation that disable a replication of files to Arweave if they are bigger than 100KB

docs: ✏️ add warnings about upload quotas and Arweave limitation

---

src/styles/blogPage.css

Change blog link colors to be more subtle and pleasant to read.
| Before | After |
| ------ | ------ |
| ![image](https://github.com/user-attachments/assets/00a9af87-742c-45b1-8259-63fa337043bf) | ![image](https://github.com/user-attachments/assets/7fc39ba7-ef90-4483-8dd2-62e895557ce0) |
- Added `text-white decoration-gray-dark-8` to our `blogPage.css` anchor selector
- [AS-294](https://linear.app/fleekxyz/issue/AS-294/change-color-of-links-in-bloglanding-page-to-use-gray-rather-than)

style: 💅 blog links

---

src/components/InjectCodeCopy.astro
src/layouts/BlogPage.astro
src/layouts/DocPage.astro

Add a "copy" button to code blocks in blog and docs
- Hacking the DOM
- [AS-295](https://linear.app/fleekxyz/issue/AS-295/add-clipboard-icon-copy-code-snippet-on-click)
https://github.com/user-attachments/assets/2d32b987-b177-495e-bcb7-a9f4f53ef6f8

feat: copy code blocks

---

.github/actions/spell-checker/ignore_words.txt
.github/workflows/support-service-update.yml
README.md
Services/ZenDesk/README.md
Services/ZenDesk/scripts/add-env-vars
Services/ZenDesk/support.service

Extend environment variable support via CI/CD for ZenDesk's service
- Add environment variables in CI/CD as env. variables and secrets where it applies
- Created a script to automate the env variable update process on remote service via CI/CD
-  Update Systemd service template by including the EnvironmentFile= directive which value corresponds to the environment variables file created in the automation script
- Update docs
- [AS-303](https://linear.app/fleekxyz/issue/AS-303/extend-environment-variable-support-via-cicd-for-zendesks-service)

chore: 🤖 Extend environment variable support via CI/CD for ZenDesk's service

---

src/components/Changelog/ChangelogItem.astro
src/pages/api/changelog-batch/[batch].astro
src/pages/api/changelogs.json.ts
src/pages/changelog.astro

Changelogs are now paginated and can be requested by clicking on `Load more` button. Initial batch of 3, with increments of 3 after.
Additionally, there's now a public endpoint for when we want to fetch changelog items on the dashboard too (not working yet, only when changelog is in prod): 
```
GET https://fleek.xyz/api/changelogs.json
```
- Done B
- Done C
- [AS-284](https://linear.app/fleekxyz/issue/AS-284/implement-pagination-logic)

feat(changelog): add changelog pagination

---

src/pages/changelog.astro

Removes the dot in the url path from `generateChangelogDetailsUrl`

fix: relative path

---

astro.config.mjs

Removes the previous redirect rule from `/changelog` to `/blog/announcements`

fix: remove changelog redirect from config

---

README.md
scripts/check-file-size.ts

Accept video assets of x size, higher then default assets.
- Modify asset validation
- Set max accepted video file size of 6 mb
- [AS-315](https://linear.app/fleekxyz/issue/AS-315/accept-video-assets-of-x-file-size-higher-then-default-assets)

refactor: 💡 accept video assets of x size

---

src/layouts/BaseHtml.astro

Reuse the same fallback from `og:image` on `twitter:image`
**Before:**
**After:**

fix: twitter img fallback on BaseHtml template

---

src/layouts/BaseHtml.astro

Fixes twitter url fallback from BaseHtml to match og url implementation (check `undefined` in twitter:image)
Before
After

fix: twitter url fallback

---

src/layouts/DocPage.astro
src/layouts/Page.astro
src/pages/billing/[...slug].astro
src/pages/blog/[...slug].astro
src/pages/blog/[category].astro
src/pages/changelog/[...slug].astro
src/pages/guides/[...slug].astro
src/pages/index.astro
src/pages/pricing.astro
src/pages/references/[...slug].astro
src/utils/generateFullSlug.ts

- Made `Page.astro` more generic to forward props to `BaseHtml`
- Added a helper `generateFullSlug` for slug pages to join the base path with the content slug
- previously, navigating to `/blog/*` would generate metadata disregarding `/blog/`, i.e.: https://fleek.xyz/blog/learn/hottest-tends-2024-serverless-cloud-computing/ had the metadata of 
`<meta property="og:url" content="https://fleek.xyz/learn/hottest-tends-2024-serverless-cloud-computing">`
- Added this helper on all slug pages

feat: add generateFullSlug for metadata purposes

---

src/content/docs/CLI/Applications/index.md
src/content/docs/CLI/Domains/index.md
src/content/docs/CLI/Edge SGX/index.md
src/content/docs/CLI/Functions/index.md
src/content/docs/CLI/PAT/index.md
src/content/docs/CLI/Projects/index.md
src/content/docs/CLI/Sites/index.md
src/content/docs/CLI/Storage/index.md
src/content/guides/getting-started-fleek-functions-edge-sgx/index.md

This pull request adds in a basic documentation for the Edge SGX feature on the Fleek CLI

feat: add sgx overview docs to CLI section and fix typo on sgx guide

---

src/components/Sidebar.tsx
src/layouts/DocPage.astro

This PR adds a functionality to make the sidebar on desktop be expanded by default so users are able to get a very good view of what the documentation entails and can interact with the pages without having to tediously open each one.
- Wrote some logic to ensure that the "open" attribute of the `<details>` HTML element can open and close based on the viewport and that the open and close still work as expected
- Made the container auto-scrollable to ensure that when items exceed the viewport, the items scroll
- [Set up the sidebar of the docs to be expanded by default on desktop view](https://linear.app/fleekxyz/issue/PLAT-1464/set-up-the-sidebar-of-the-docs-to-be-expanded-by-default-on-desktop)
https://github.com/user-attachments/assets/85996e88-92d9-4e03-a118-b5b092950f9a

feat: Set up the sidebar of the docs to be expanded by default on desktop view

---

.github/workflows/release-by-develop-hash.yml
.github/workflows/search-indexer.yml

Dispatch event to trigger indexer, instead of relying on push listener which seem to fail after applying the release by develop hash process.
- Create dispatch by event name
- Add listener
- [AS-330](https://linear.app/fleekxyz/issue/AS-330/prevent-mellisearch-test-from-failing-on-fleek-platformwebsite-prs)
- [AS-333](https://linear.app/fleekxyz/issue/AS-333/use-event-to-dispatch-indexer)

chore: 🤖 Create event dispatcher post "Release by Dev Hash" to trigger indexer listener

---

.github/actions/spell-checker/ignore_words.txt
src/content/guides/fleek-functions-http-types/index.md
src/content/guides/how-to-open-websocket-in-fleek-function/index.md
src/content/guides/running-bundled-webpack-functions-on-fleek/index.md

The bundle parameter has changed in https://github.com/fleek-platform/cli/pull/34, thus the documentation has to reflect the changes.
⚠️ Related to https://github.com/fleek-platform/cli/pull/34
- Update guides
- [PLAT-1273](https://linear.app/fleekxyz/issue/PLAT-1273/the-bundle-parameter-is-not-intuitive-due-to-negation-eg-nobundle)

docs: 📝 Update Bundle parameter syntax

---

.github/workflows/release-by-develop-hash.yml
.github/workflows/search-indexer.yml

The "Release by Hash" is to serve the Product team. It's a custom process. When successful, it merges a subset of develop into main branch. We call this a "Release to production". For some reason, since this was introduced, the CI/CD Search Indexer stopped working, e.g. "on: push". The issue was reported to GitHub and seems that it has a limitation that prevents it from triggering "on: push" with the right context. See [here](https://github.com/orgs/community/discussions/139698)
- Update workflows to trigger event by a name in post release success, and listen to event name in ci/cd of search
- Updated documentation
- [AS-335](https://linear.app/fleekxyz/issue/AS-335/cicd-indexation-run-on-event)

chore: 🤖 CI/CD Indexation run on event

---

src/components/Pricing/index.tsx
src/components/PricingCard.tsx

- Removed `+ Overage` copy from pricing table
- Matched LP title and subtitle styling for pricing page
- Done B
- Done C

chore: remove overage from pricing table

---

src/components/LandingPage/Hero.tsx
src/components/OnPageNavigation/TableOfContents.tsx
src/styles/docPage.css

Small design tweaks for landing page and docs
✅ 1. Replace carets with dots on in-page navigation to signify that these are not accordions
✅ 2. Have the dot aligned with the first line of text rather than the vertical midpoint
----
✅ 3. On mobile, show more of the product image by reducing the size of the image.
----
✅ 4. Add space between icon and text on callouts ('i' and 'Info' here)
- [PLAT-1563](https://linear.app/fleekxyz/issue/PLAT-1563/fast-follow-design-tweaks-for-landing-page-and-docs)

style: fast follow design tweaks for landing page and docs

---

src/styles/docPage.css

On Docs/SDK/Overview, there is a layout break from long unique words like variables that can be greater than the device width. This PR fixes this by forcing line break on word level. 
Before:
After:
- [PLAT-1585](https://linear.app/fleekxyz/issue/PLAT-1585/docs-add-line-break-for-long-words-like-variables-so-the-layout-wont)

fix: add line break for long words, like variable names

---

.gitignore
src/components/BlogPosts.astro
src/components/Tags.tsx
src/pages/blog/[...slug].astro

Add tags to blog articles
- Created Tag component
- Add tag component to blog article 
- Add tag component to blog article card
- [Ticket 1](https://linear.app/fleekxyz/issue/PLAT-1599/add-tags-to-blog-posts-on-the-fleekxyz-blog)

feat(PLAT-1599): :sparkles: Add support for blog tags

---

src/content/docs/CLI/Edge SGX/index.md

Adds notice and link to sgx edge doc about sgxkit

docs: add warning only rust-based sgxkit is officially supported

---

.github/workflows/build-dry-run.yml
README.md
src/components/BiweeklySubscription.tsx
src/components/Button.tsx
src/components/Footer/index.tsx
src/components/Links/LinkButton.tsx
src/components/Links/SocialButton.tsx
src/components/Links/index.tsx
src/layouts/BaseHtml.astro
src/layouts/Page.astro
src/pages/links.astro
src/settings.json
tailwind.config.mjs

feat: links page

---

package.json
src/components/InjectCodeCopy.astro
src/layouts/BaseHtml.astro
src/layouts/DocsHtml.astro

This PR changes the copy UX of docs codeblocks to a more minimalist approach. Instead of popping a toaster and visually selecting the code content with a yellow background, we now change the copy to clipboard icon to a checked icon to signal the content was copied. After 3 seconds, the original icon comes back. 
**Before:**
**After:**
https://github.com/user-attachments/assets/416c08e0-1070-4c0c-a47c-75ca0aae0176
- [PLAT-1809](https://linear.app/fleekxyz/issue/PLAT-1809/modify-copying-ux-from-docs-to-highlight-copied-code-block-with-yellow)

feat: modify copying ux of docs codeblocks

---

src/components/Footer/config.ts
src/components/Navbar/config.ts

Fix about link. It should be on the Footer but added it to the navbar instead by mistake.
- Deleted the link from the navbar and added to the footer
- [PLAT-1810](https://linear.app/fleekxyz/issue/PLAT-1810/add-an-about-page-using-the-finalized-content

fix(PLAT-1810): fix wrong hyperlinks

---

src/components/Links/index.tsx

Featured post in Links page looks too large and results in a scrollbar visible in some screens.
- Adjust Featured post image max-height and max-width in Links page
- N/A

feat: adjust featured post image in links page

---

src/layouts/LandingPageHtml.astro

Based on complaints raised by Royce and Azul, I went to `opengraph.xyz` and saw that the meta and twitter og images were broken; missing a `/`:
```html
<title>Fleek | Build and deploy performant apps</title>
<meta name="description" content="Fleek makes it easy to ship performant apps in minutes. Deploy instantly, run globally, scale automatically.">
<meta property="og:url" content="https://fleek.xyz">
<meta property="og:type" content="website">
<meta property="og:title" content="Fleek | Build and deploy performant apps">
<meta property="og:description" content="Fleek makes it easy to ship performant apps in minutes. Deploy instantly, run globally, scale automatically.">
<meta property="og:image" content="https://fleek.xyzimages/fleek-meta.png?202406061658">
<meta name="twitter:card" …
```

fix: og image breaking

---

src/content/blog/announcements/comparing-ssr-frameworks-nextjs-nuxtjs-angular/index.md
src/content/blog/announcements/fleek-network-50-use-cases/index.md
src/content/blog/learn/best-serverless-computing-platforms-2024/index.md
src/content/blog/learn/edge-computing-challenges-fleek/index.md
src/content/blog/learn/hottest-trends-2024-serverless-cloud-computing/index.md
src/content/blog/learn/open-source-self-hosted-web-applications-frontend/index.md
src/content/blog/learn/server-side-rendering-explained/index.md
src/content/blog/learn/server-side-vs-client-side-rendering-comparison/index.md
src/content/blog/learn/top-serverless-frameworks/index.md
src/content/blog/learn/understanding-ipfs-storage-fleek/index.md
src/content/blog/learn/vercel-alternatives-guides/index.md
src/content/blog/learn/who-is-hosting-this-website-guide/index.md
src/content/config.ts
src/pages/blog.astro
src/styles/typography.css

- Extended our blog collection schema to have an optional flag of `isSeoPost`
- This flag signals SEO-driven posts which should be hidden from the `/blog` listing, but still appear under its category listing, like `/blog/learn`, `/blog/announcements`, etc
https://github.com/user-attachments/assets/f85b185d-d170-4e3e-aebd-fda6f68c4511
- [AS-353](https://linear.app/fleekxyz/issue/AS-353/implement-hide-from-main-tag-to-hide-seo-posts-from-blog-page)

feat: hide SEO-driven posts from /blog

---

src/content/blog/announcements/comparing-ssr-frameworks-nextjs-nuxtjs-angular/index.md
src/content/blog/announcements/fleek-network-50-use-cases/index.md
src/content/blog/learn/best-serverless-computing-platforms-2024/index.md
src/content/blog/learn/edge-computing-challenges-fleek/index.md
src/content/blog/learn/hottest-trends-2024-serverless-cloud-computing/index.md
src/content/blog/learn/open-source-self-hosted-web-applications-frontend/index.md
src/content/blog/learn/server-side-rendering-explained/index.md
src/content/blog/learn/server-side-vs-client-side-rendering-comparison/index.md
src/content/blog/learn/top-edge-computing-platforms-2024/index.md
src/content/blog/learn/top-serverless-frameworks/index.md
src/content/blog/learn/understanding-ipfs-storage-fleek/index.md
src/content/blog/learn/vercel-alternatives-guides/index.md
src/content/blog/learn/who-is-hosting-this-website-guide/index.md
src/content/config.ts
src/layouts/BaseHtml.astro
src/layouts/BlogPage.astro
src/layouts/ChangelogPage.astro
src/pages/blog.astro
src/pages/blog/[...slug].astro
src/pages/changelog/[...slug].astro
src/pages/guides/[...slug].astro
src/pages/references/[...slug].astro

The current state of content (most especially blogs, guides, references, and changelogs) takes whatever title the `title` value is in the frontmatter of the content, but, there is no such chance for any of them to have a custom value either for marketing or SEO reasons. This PR enables that:
And it renders like this:
-Added `customMetaTitle` to the Zod schema
- Passed the props from the content, to the page setup and layout
- [Add an option to blogs to set a different meta title when the blog title exceeds the character limit](https://linear.app/fleekxyz/issue/AS-359/add-an-option-to-blogs-to-set-a-different-meta-title-when-the-blog)

feat: add custom meta-title to content schema

---

src/components/AuthProvider/AuthProvider.tsx

- Website uses font-size of 62.5%, altering the dynamic widget fonts and making it very small. This PR solves it by increasing the modal scale
Before:
After:

fix(eliza): dynamic size

---

src/components/Eliza/api/api.ts

API changed to be camel case for consistency across all our APIs.
- Replaced params for camel case

chore: move eliza params to camel case

---

src/content/docs/ai-agents/Upload Characterfile/index.mdx
src/content/guides/eliza-guide/index.md

This PR adds in the docs callout for the settings key for the upload characterfile option of the Agents deployments and it also adds in a call out that links to the docs in the conclusion:

chore: add docs callout and link to docs in quickstart guide's conclusion

---

src/components/Eliza/components/Characterfile.tsx
src/components/Eliza/components/GetStarted.tsx
src/components/Eliza/components/UploadPage.tsx
src/settings.json

- The help links along the flow now points to our guides instead of Eliza docs
- Done B
- Done C

chore(eliza): change eliza docs links with fleek guides

---

.github/workflows/build-dry-run.yml
package-lock.json
src/components/AuthProvider/AuthProvider.tsx
src/components/AuthProvider/api/api.ts
src/components/AuthProvider/useAuthentication.ts
src/components/Eliza/api/api.ts
src/components/Eliza/components/DeploymentStatus.tsx
src/components/Eliza/index.tsx
src/components/Navbar/index.tsx
src/hooks/useProjects.ts
src/settings.json

- Moved project management from AuthProvider to new useProjects hook
- Updated AuthProvider, Eliza, and Navbar components to use useProjects
- Centralized API endpoint URLs using environment variables
- Simplified settings.json by removing redundant configurations
- Enhanced API modules to utilize API_BASE_URL for consistency
- Improved state management in authentication flow
- N/A

refactor(auth): :recycle: extract project logic into useProjects hook and centralize API endpoints

---

README.md

Missing PUBLIC_UI_APP_URL env var in documentation
- added it
N/A
N/A
N/A

docs(docs): :memo: Add missing env var to the documentation

---

src/components/Eliza/components/Dropdown.tsx

- We are expanding our model providers and clients, so it's a good time to add a max height to our dropdown content to avoid issues of overflown content out of the viewport :)
Before:
After:
- Done B
- Done C

style(eliza): add max height to dropdown content

---

src/components/Eliza/components/Characterfile.tsx
src/components/Eliza/components/Collapsible.tsx
src/components/Eliza/components/FormField.tsx
src/components/Eliza/components/PluginsDropdown.tsx
src/components/Eliza/components/ReviewPage.tsx
src/components/Eliza/utils/constants.ts
src/components/Eliza/utils/schema.ts
src/components/Eliza/utils/transformData.ts
src/components/Eliza/utils/types.ts

- Added supported plugins to constants
- Added plugin dropdown to builder form
- Added validation for the final characterfile json
- Added better error visualization in review page
https://github.com/user-attachments/assets/00055785-17f8-461e-a5aa-8b6126c318f9
https://github.com/user-attachments/assets/4f240f4e-8b78-486d-82c3-99ec1278ce62
👆 disregard errors in review page from this demo
- [PLAT-2015](https://linear.app/fleekxyz/issue/PLAT-2015/add-plugins-support-to-builder-form-and-upload-characterfile)

feat(eliza): add plugins support

---

README.md
src/components/AgentsUI/index.tsx
src/components/Eliza/ElizaIntegrationLayer.tsx
src/components/Eliza/api/index.ts
src/components/Eliza/components/SubscriptionModal.tsx
src/pages/eliza.astro
src/utils/promotekit.ts

Promotekit runtime getter.
- Create getter for promote kit
- Fallback to cookie as persistence layer on promotekit failure
- [PLAT-2041](https://linear.app/fleekxyz/issue/PLAT-2041/re-implement-promotekit-runtime-with-getter-and-cookie-fallback)
> Runtime example:
https://github.com/user-attachments/assets/e8590c9c-a0bf-4a2e-9bcf-cd647fda7797
> Window object promotekit referral value
> promotekit referral from cookies for persistency on promotekit failure

chore: 🤖 Promotekit runtime with getter and cookie fallback

---

src/components/Templates/TemplateDetails/TemplateSpecs.tsx
src/templates/production.json
src/templates/staging.json

Template's creation dates are stored as plain text and the format is not correct.
- Store template's creation dates as ISO dates instead of plain text
- Format them in JSX using existing utility - remove leading zero in day and comma between month and day
- [PLAT-2065](https://linear.app/fleekxyz/issue/PLAT-2065/when-a-template-creation-date-has-a-leading-zero-in-the-day-ex)
https://fleek.xyz/templates/gatsby-boilerplate/

refactor(templates): store creation dates as ISO dates instead of plain text

---

src/components/Navbar/config.ts
src/components/Navbar/index.tsx
src/hooks/useSession.ts

On mobile, the navbar doesn't have enough space to fit the logo, project switcher, and authentication buttons (Login, Signup, Logout). This PR moves the authentication buttons into a new **"Account"** section within the hamburger menu. This change only applies to mobile (`<md`), while the desktop layout remains unaffected.  
- Hide authentication buttons in the navbar on mobile.  
- Add an **"Account"** section to the hamburger menu.  
- Include **Login, Signup, Logout, and Dashboard** buttons in this section.  
- Introduce a `useSession` hook to centralize and reuse authentication logic.  
- Implement authentication functionality using `useSession` and `LoginProvider`.  
- [AS-381](https://linear.app/fleekxyz/issue/AS-381/fix-login-buttons-in-website-mobile-view)
Optionally, provide …

feat(navbar): move authentication buttons to hamburger menu on mobile

---

package-lock.json
package.json

The login modal is broken on mobile because the `login-button` package currently applies a `scale(1.5)` CSS override. This was initially added to compensate for the modal using `rem` units while the website's `<html>` tag has a `font-size` of 62.5%, which makes the modal appear too small. However, scaling is not a reliable solution, as it causes the modal to overflow beyond the screen boundaries on mobile.  
- Introduced `loginModal.css`, which contains only the necessary CSS overrides to fix the modal.  
- By overriding, I just replaced `rem` units with `em` to make the modal’s sizing independent of the `<html>` font size.  
- Overrides are, where possible, css variables provided by dynamic. Where not, plain css rules.
- Set a `font-size` of `16px` on the modal's parent `<div>`, ensuring …

chore(package): update login-button to 2.0.3

---

package-lock.json
package.json

2.0.5 fixes the font-size of button "Re-send code" and the re-rendering when isLoading from LoginProvider changes
ref:
https://github.com/fleek-platform/login-button/pull/15
https://github.com/fleek-platform/login-button/pull/14
- Updated login-button dependency to 2.0.5
- [PLAT-2086](https://linear.app/fleekxyz/issue/PLAT-2086/authentication-modal-overflows-outside-the-screen-on-mobile)

chore(package): update login-button to 2.0.5

---

package-lock.json
package.json

Upgrades npm package @fleek-platform/login-button to 2.0.7.
ref: 
https://github.com/fleek-platform/login-button/commit/3ce599dffccee793b649e253353c7452db7d1069
https://github.com/fleek-platform/login-button/commit/77ac7237c806acd4f182d9dc2e63e5e79cf368b0
- Update package and package-lock with new version of dependency
- [PLAT-2096](https://linear.app/fleekxyz/issue/PLAT-2096/fix-login-button-eslint-errors-blocking-commits-and-merges)

chore(package): update login-button to 2.0.7

---

src/content/docs/Platform/index.mdx

Changes "Gatsby" with "Next.js"
- Done B
- Done C
- [PLAT-2123](https://linear.app/fleekxyz/issue/PLAT-2123/docs-replace-gatsby-with-nextjs-as-an-example

docs: replace gatsbyjs with nextjs

---

package-lock.json
package.json

- Refresh agent logs didn't refetch. see https://github.com/fleek-platform/agents-ui/pull/77
- Bumped package version
Related PLAT-2169

chore: 🤖 Bumped agents-ui to 3.8.3

---

src/pages/eliza.astro

Fixes horizontal padding on mobile for `/eliza` flow.
- Added `md:` breakpoint
N/A Direct feedback.

fix: 🐛 Adds back /eliza horizontal padding below md: breakpoint

---

package-lock.json
package.json

Updates @fleek-platform/agents-ui to 3.9.3.
diff:
https://github.com/fleek-platform/agents-ui/compare/48b567415fc39e3eb663ab19993dabe5356fe8d3...13b86c15c022d03599b8aab8024c56725666f83f
- Updated package and package-lock.
- [PLAT-2187](https://linear.app/fleekxyz/issue/PLAT-2187/agents-ui-form-drop-downs-broken-eg-has-transparent-background)

chore: update agents-ui to 3.9.3

---

src/content/docs/ai-agents/Agents-APIs/index.mdx
src/content/docs/index.mdx

This pull request fixes the quickstart guide typo and the base API docs link in the agents API docs.
- Fix quickstart card typo
- Fix link
- [Add references to AI agent hosting to the fleek.xyz/docs start page (Quick Start guide)](https://linear.app/fleekxyz/issue/PLAT-2190/add-references-to-ai-agent-hosting-to-the-fleekxyzdocs-start-page)

docs: fix link and typo

---

src/content/troubleshooting/eliza/eliza-deployment-troubleshooting/index.md

Removed suggestion to avoid 2fa, as it actually helps avoid login issues.
Improving the existing troubleshooting guide to better reflect the use of 2FA with agents.
- Done B
- Done C

docs: removed suggestion to avoid 2fa

---

src/utils/templates.ts

Missing slash in template get URL
- Add slash to URL getter
- [PLAT-2239](https://linear.app/fleekxyz/issue/PLAT-2239/missing-slash-in-template-get-url)

fix: 🐛 Missing slash in template get URL

---

src/utils/templates.ts
src/utils/url.ts

Handle `PUBLIC_UI_APP_URL` env var with or without trailing slash.
- Done B
- Done C

fix: handle trailing slash for template deployment url

---

public/favicon/site.webmanifest

Fixes favicons paths in site.webmanifest
- Done B
- Done C

fix(site.webmanifest): 512px and 192px favicon paths

---

package-lock.json
package.json

Updates @fleek-platform/agents-ui to latest (4.10.3)
4.10.1~4.10.3 diff:
https://github.com/fleek-platform/agents-ui/compare/191677fc4bca38afffde2ac073fee05712fe9090..b1db94b32c5b3a59fe7e4625b70c7f6854e7d156
- npm i @fleek-platform/agents-ui@latest

chore: update agents-ui to 4.10.3

---

package-lock.json
package.json

Updates agents-ui to 5.0.2
diff:
https://github.com/fleek-platform/agents-ui/compare/1314116ec420293675501e157d1f0185b066f3a0..73f7695ad055943687ff9ab923acbb9ab4956aeb
- Done B
- Done C
- [closes PLAT-2412](https://linear.app/fleekxyz/issue/PLAT-2412/website-update-agents-ui-to-502)

chore: update agents-ui to 5.0.2

---

.github/workflows/build-dry-run.yml
.github/workflows/commit-checkups.yml
package-lock.json
package.json
src/components/AgentsUI/index.tsx
src/pages/eliza.astro

- Bumps `agents-ui` to `6.3.0`
- tl;dr what's new:
- Router capabilities
- Agent chat
- Support for different elizaOS versions
- Bug fixes
https://github.com/fleek-platform/agents-ui/blob/main/CHANGELOG.md (`5.0.2` onwards)

chore: bump agents-ui package to 6.3.0

---

package-lock.json
package.json

Updates @fleek-platform/agents-ui to 6.3.1
diff:
https://github.com/fleek-platform/agents-ui/compare/ccd050b28ac7dd918d0c938e6c6d08fd8149deba..0b0fc342513b7d3e291922a20e22ea5a823ba31d
- Done B
- Done C
- [PLAT-2420](https://linear.app/fleekxyz/issue/PLAT-2420/agents-ui-landing-panel-options-items-width-issue)

chore: update agents-ui to 6.3.1

---

package-lock.json
package.json

- Updates agents-ui to 6.6.1
- Done B
- Done C

chore: bump agents ui to 6.6.1

---

src/components/Announcement.tsx
src/components/LandingPage/Hero.tsx
src/pages/index.astro

The marquee was relying on the viewport resolution to animate or not.
- Since the marquee was placed inside the hero, and the behavior relies on the browser, added instruction to hydrate the hero in the client;
- Instead of relying just on the viewport size, the marquee animation now relies on the real dimensions of the elements (if text overflows, turns on the animation)
- [PLAT-877](https://linear.app/fleekxyz/issue/PLAT-877/fix-announcement-banner-on-landing-page-section-at-medium-viewport)
- **before** with *short text*
- **before** with *long text*
- **after** with *short text*
- **after** with *long text*

fix(marquee): :bug: fix line break in marquee

---

package-lock.json
package.json

- Bumps dashboard version to `0.9.3` to switch promotekit with tolt as affiliate program
- [PLAT-2485](https://linear.app/fleekxyz/issue/PLAT-2485/incorporate-affiliate-program-to-app-and-landing)

chore: bump dashboard version

---

README.md

Adds -E flag so that the external app installed hasn't version prepended by caret (`^`).
- Done B
- Done C

docs(readme): add `-E` flag to external app install command

---

package-lock.json
package.json

- Downgrades agents UI to same version as prod, so we can unblock growth on the autofun partnership announcement
- Done B
- Done C

chore: downgrade agents ui to 8.2.0

---

src/layouts/DocPage.astro
src/pages/index.astro

due to domain migration the landing page in `resources.fleek.xyz` should be the documentation page
- Done B
- Done C

feat(NA): in the new domain the landing page should be the /docs page
